#!/bin/bash

set -exuo pipefail
shellcheck -x "$0"

readonly TARGET_ARCH=aarch64-unknown-linux-gnu

pushd "$HOME"/learning-rust/bottymcbotface-rs

cross build --release --target ${TARGET_ARCH}

rsync -azvhP \
    ./target/${TARGET_ARCH}/release/bottymcbotface-rs \
    pi:bot/release/

ssh -t pi "sudo systemctl restart bottymcbotface ; systemctl status bottymcbotface"

popd
