name: Rust

on:
  push:
    branches: [ "main", "test-cicd" ]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal\
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.5
    - name: Compile
      id: compile
      # You may pin to the exact commit or the version.
      # uses: rust-build/rust-build.action@6febf1b0ed6499a46610b58ef9d810398e75f3c2
      uses: rust-build/rust-build.action@v1.4.5
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: x86_64-unknown-linux-musl
        UPLOAD_MODE: none
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Binary
        path: |
          ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          ${{ steps.compile.outputs.BUILT_CHECKSUM }}
        if-no-files-found: error
